### PR TITLE
feat: documentation website

### PR DESCRIPTION
**Pull request by mtdvlpr**
I've created a basic setup for a documentation website using [VitePress](https://vitepress.dev/). VitePress is the official documentation builder of Vue. I've added a home, about and faq page and setup the internationalization. The theme/styling can be customized to align with M³ styling. You can easily work on the website locally with the `docs:dev` script. It has built-in search, light/dark and responsiveness.

For deployment, perform the steps at https://vitepress.dev/guide/deploy#github-pages

I've also optimized the Electron dependencies (see [Quasar Docs](https://quasar.dev/quasar-cli-vite/developing-electron-apps/configuring-electron/#dependencies-optimization) for more info). When Electron uses a new dependency, it should be explicitly added in `quasar.config.js`, so that only the necessary dependencies are included in the production build.

### CODE REVIEW

**Comment by sircharlo** [comment]
Alright! This is great stuff!!
Let's give it a whirl.

**Comment by sircharlo** [comment]
@mtdvlpr FYI: the changes to the build options were actually breaking builds completely. They built fine, but the installed app would crash on load.
I've included what seemed to be the missing needed modules in dab22f63157403acb5d4e2c3e536e4dd9de8e289.
Let me know if I missed something obvious.

**Comment by mtdvlpr** [comment]
Hmm, weird. Those vue dependencies should be bundled in the ui code. Vue-i18n becomes a `vue-i18n_hash.js` file, for example. The docs also say that you only have to allow the packages that get imported in the main/preload processes. I'll experiment with it some more. Sorry for not testing it beforehand!

**Comment by sircharlo** [comment]
No worries; I was quite surprised too. I'm not sure why this happened exactly.

**Comment by mtdvlpr** [comment]
@sircharlo, I found the issue with the electron dependencies. You import `errorCatcher` in the Electron process and `errorCatcher` imports `@sentry/vue` and `@sentry/vue` imports `vue`, etc. It should probably be rewritten so that those Electron errors are either captured with [Sentry/electron](https://docs.sentry.io/platforms/javascript/guides/electron/) or passed to the UI and captured there.

**Comment by mtdvlpr** [comment]
Check out [these docs](https://docs.sentry.io/platforms/javascript/guides/electron/#framework-specific-sdks) for combining Sentry/electron with Sentry/vue.

**Pull request merged**
