### PR TITLE
refactor: remove dayjs and quasar lang dependency

### PR DESCRIPTION
**Pull request by mtdvlpr**
I've rewritten the localized dates code to use a combination of user translated keys and the quasar built-in date util. This has several benefits:

- One dependency (dayjs) less to import and maintain
- No need to import Quasar language packs
- All languages that we support can have translated days instead of depending on Quasar and Dayjs to support the language

A little bit of info:

I used what's called a composable. A composable is like a reusable building block for a component. Just like components are building blocks for pages. Composables can be recognized by the `useSomething` naming convention. `useI18n` and `useSomeStore` are also composables.

The difference between composables and normal utility functions is that composables can use Vue features, like `computed`, `onMount`, `ref` and `watch`.

### CODE REVIEW

**Comment by sircharlo** [comment]
Interesting refactor! I like how it simplifies dependencies somewhat.
I made the calendar popups more minimal, which removes the problem of setting the date format in the calendar popup.

Question: 
- What is 'days-plural' used for?

**Comment by mtdvlpr** [comment]
> Interesting refactor! I like how it simplifies dependencies somewhat. I made the calendar popups more minimal, which removes the problem of setting the date format in the calendar popup.
> 
> Question:
> 
> * What is 'days-plural' used for?

Oops, I overlooked that one. You could return it if you like if it's refactored like [here](https://github.com/sircharlo/mmm-refactor/pull/275/files#diff-a2a71144f5ff4687d12fc7c400d566b93e3f5e5a28e5fd1af3e4d874448cf649).

As for the `days-plural`, I'm not sure. It's present in the Quasar language pack under `date`, so I assume it's used somewhere. Maybe in a date range component or for the date util when calculating the difference between two dates? As of now, it's not used, so it can be removed.

**Comment by mtdvlpr** [comment]
> Also, would it be terribly complicated to have the days under each congregation on the congregation selector page be displayed in the UI language of that congregation?

I believe you can use the `t` function with a locale other than the current. I'll play around with it.

**Comment by mtdvlpr** [comment]
> > Also, would it be terribly complicated to have the days under each congregation on the congregation selector page be displayed in the UI language of that congregation?
> 
> I believe you can use the `t` function with a locale other than the current. I'll play around with it.

Done :)

**Comment by mtdvlpr** [comment]
Don't forget to add the new locale strings to `meeting-media-manager/new-strings` :)

**Comment by mtdvlpr** [comment]
I have resolved the merge conflict

**Comment by sircharlo** [comment]
Thanks so much! This is coming together so nicely.

**Pull request merged**
