### PR TITLE
fix: correctly integrate Sentry for Electron

### PR DESCRIPTION
**Pull request by mtdvlpr**
I cleaned up the public folder, added the logo to home and added some emojis and custom containers.

You can find more VitePress Markdown features at: https://vitepress.dev/guide/markdown
The icons at home I got from: https://emojipedia.org/

I also fixed the Sentry integration for Electron by adding the Sentry/electron package and removing UI dependencies from the Electron process (Sentry/vue and quasar)

### CODE REVIEW

**Comment by sircharlo** [comment]
Very cool!
When I create a page in English, how do I go about adding that page in all the language folders? Manually?

**Comment by mtdvlpr** [comment]
Yeah, for now, it's manual labor. If you don't add them, they'll get a 404 error on that page. Once Crowdin is configured again, it will be automated.

**Comment by mtdvlpr** [comment]
You could, of course, add them already to mlthr meeting-media-manager repo like you do with the app strings.

**Comment by sircharlo** [comment]
> You could, of course, add them already to mlthr meeting-media-manager repo like you do with the app strings.

Meh. We're close to publishing anyways. I think I'll wait for the refactor to be released before telling Crowdin what to look for.

**Comment by sircharlo** [comment]
Thanks for fixing the Sentry + Electron bug; makes perfect sense.

**Comment by mtdvlpr** [comment]
> > You could, of course, add them already to mlthr meeting-media-manager repo like you do with the app strings.
> 
> Meh. We're close to publishing anyways. I think I'll wait for the refactor to be released before telling Crowdin what to look for.

Before activating Crowdin, I would suggest removing all the other locale pages so that Crowdin can correctly process them as untranslated.

**Pull request merged**
